apiVersion: v1
kind: Service
metadata:
  name: wordpress-site
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv-claim
spec:
  storageClassName: portworx-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress-rc
spec:
  replicas: 1
  selector: 
    app: wordpress
  template:
    metadata:
      name: wordpress-rc
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-pv-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mariadb
        - name: WORDPRESS_DB_USER
          value: wp-kube-usr
        - name: WORDPRESS_DB_PASSWORD
          value: q1w2e3r4t5
        - name: WORDPRESS_DB_NAME
          value: wp-kube-db
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: wordpress-pv-storage
