#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: wordpress
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv-claim
spec:
  storageClassName: portworx-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
#  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    name: wordpress
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
#  namespace: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          # Use secret in real usage
        - name: WORDPRESS_DB_PASSWORD
          value: P4$$W0RDD
        - name: WORDPRESS_DB_HOST
          value: mysql
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-volume-01
          mountPath: /var/www/html
#        resources:
#          requests:
#            memory: "2048Mi"
#            cpu: "250m"
#          limits:
#            memory: "2048Mi"
#            cpu: "250m"
      volumes:
        - name: wordpress-volume-01
          persistentVolumeClaim:
            claimName: wordpress-pvc-01-00
